django/properties/urls.py
from django.urls import path

from properties.views import fotos

app_name = 'properties'
urlpatterns = [
    path('<id>/fotos/', fotos, name='fotos'),
]

django/property_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', admin.site.urls),
    path('properties/', include('properties.urls'))
]

admin.site.site_header = 'Gerenciador de imóveis'
admin.site.site_title = 'Administração'

django/properties/models.py
from django.db import models


# Create your models here.
class Imovel(models.Model):
    UF = models.CharField('UF', max_length=2)
    cidade = models.CharField('Cidade', max_length=50)
    cep = models.CharField('CEP', max_length=10, blank=True, null=True)
    nome = models.CharField('Nome', max_length=100)
    descricao = models.TextField('Descrição', blank=True, null=True)
    logradouro = models.CharField('Logradouro', max_length=50)
    numero = models.PositiveIntegerField('Número', blank=True, null=True)
    complemento = models.CharField('Complemento', max_length=30, blank=True, null=True)
    status = models.ForeignKey('config.Status', on_delete=models.PROTECT, null=True)
    contato = models.TextField('Contato', blank=True, null=True)

    class Meta:
        verbose_name = 'Imóvel'
        verbose_name_plural = 'Todos Imóveis'

    def __str__(self):
        return '{}, {}, {}, {}/{}'.format(self.nome, self.logradouro, str(self.numero), self.cidade, self.UF)


class Residencia(models.Model):
    imovel = models.OneToOneField(Imovel, on_delete=models.CASCADE)
    dormitorios = models.PositiveSmallIntegerField('Dormitórios')
    suites = models.PositiveSmallIntegerField('Suítes')
    lavabos = models.PositiveSmallIntegerField('Lavabos')
    banheiros = models.PositiveSmallIntegerField('Banheiros')
    salas = models.PositiveSmallIntegerField('Salas')
    sacadas = models.PositiveSmallIntegerField('Sacadas')
    vagas = models.PositiveSmallIntegerField('Vagas para carros')
    cozinhas = models.PositiveSmallIntegerField('Cozinhas')
    infra = models.TextField('Infraestrutura', blank=True, null=True)
    outros = models.TextField('Outros', blank=True, null=True)

    class Meta:
        verbose_name = 'Residência'
        verbose_name_plural = 'Residências'

    def __str__(self):
        return self.imovel.__str__()

    @property
    def status(self):
        return self.imovel.status


class Terreno(models.Model):
    imovel = models.OneToOneField(Imovel, on_delete=models.CASCADE)
    hectares = models.FloatField('Hectares', blank=True, null=True)
    dimencoes = models.TextField('Dimensões', blank=True, null=True)
    loteamento = models.BooleanField('Loteamento')
    casa = models.BooleanField('Possui casa?')
    plano = models.BooleanField('Plano')
    limpo = models.BooleanField('Limpo')
    limpo_texto = models.TextField('Descrição sobre a limpeza do terreno', null=True, blank=True)
    agua = models.BooleanField('Água')
    agua_texto = models.TextField('Descrição Água', blank=True, null=True)
    posicao = models.TextField('Posição solar', blank=True, null=True)


    class Meta:
        verbose_name = 'Terreno'
        verbose_name_plural = 'Terrenos'

    def __str__(self):
        return self.imovel.__str__()

    @property
    def status(self):
        return self.imovel.status


class Fazenda(Terreno):
    energia = models.BooleanField('Energia')
    animais = models.TextField('Criação de animais')
    propriedade = models.TextField('Propriedade')

    class Meta:
        verbose_name = 'Fazenda'
        verbose_name_plural = 'Fazenda'

    def __str__(self):
        return self.imovel.__str__()

    @property
    def status(self):
        return self.imovel.status

django/properties/forms.py
# coding=utf-8
from django import forms
from django.forms import widgets
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.conf import settings

from config.models import Status
from gallery.models import Foto
from properties.models import Imovel


class RelatedFieldWidgetCanAdd(widgets.Select):

    def __init__(self, related_model, related_url=None, *args, **kw):
        super(RelatedFieldWidgetCanAdd, self).__init__(*args, **kw)

        if not related_url:
            rel_to = related_model
            info = (rel_to._meta.app_label, rel_to._meta.object_name.lower())
            related_url = 'admin:%s_%s_add' % info

        # Be careful that here "reverse" is not allowed
        self.related_url = related_url

    def render(self, name, value, *args, **kwargs):
        self.related_url = reverse(self.related_url)
        output = [super(RelatedFieldWidgetCanAdd, self).render(name, value, *args, **kwargs)]
        output.append('<a href="%s" class="add-another" id="add_id_%s" onclick="return showAddAnotherPopup(this);"> ' % \
                      (self.related_url, name))
        output.append('<img src="%sadmin/img/icon_addlink.gif" width="10" height="10" alt="%s"/></a>' % (
            settings.STATIC_URL, ''))
        return mark_safe(''.join(output))


class ImovelRelatedForm(forms.ModelForm):
    UF = forms.CharField(label='UF', max_length=2, required=True)
    cidade = forms.CharField(label='Cidade', max_length=50, required=True)
    cep = forms.CharField(label='CEP', max_length=10, required=False)
    nome = forms.CharField(label='Nome', max_length=100, required=True)
    descricao = forms.CharField(label='Descrição', widget=forms.Textarea(), max_length=2000, required=False)
    logradouro = forms.CharField(label='Logradouro', max_length=50, required=True)
    numero = forms.IntegerField(label='Número', min_value=0, required=False)
    complemento = forms.CharField(label='Complemento', max_length=30, required=False)
    status = forms.ModelChoiceField(label='Status', queryset=Status.objects.all(),
                                    widget=RelatedFieldWidgetCanAdd(Status))
    contato = forms.CharField(label='Contato', max_length=500, widget=forms.Textarea(), required=False)

    fotos = forms.ImageField(label='Adicionar várias fotos', required=False, widget=widgets.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        exclude = ['imovel']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        try:
            self.initial['UF'] = self.instance.imovel.UF
            self.initial['cidade'] = self.instance.imovel.cidade
            self.initial['cep'] = self.instance.imovel.cep
            self.initial['nome'] = self.instance.imovel.nome
            self.initial['logradouro'] = self.instance.imovel.logradouro
            self.initial['numero'] = self.instance.imovel.numero
            self.initial['complemento'] = self.instance.imovel.complemento
            self.initial['status'] = self.instance.imovel.status
            self.initial['contato'] = self.instance.imovel.contato
            self.initial['descricao'] = self.instance.imovel.descricao
        except:
            pass


class ImovelForm(forms.ModelForm):
    fotos = forms.ImageField(label='Adicionar fotos', required=False, widget=widgets.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = Imovel
        fields = '__all__'

django/properties/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from gallery.models import Foto
from properties.models import Imovel


def fotos(request, id):
    imovel = get_object_or_404(Imovel, id=id)
    context = {
        'imovel': imovel,
        'fotos': Foto.objects.filter(imovel=imovel)
    }
    return render(request, 'properties/fotos.html', context=context)

django/properties/templates/properties/changeform.html
{% extends 'admin/change_form.html' %}


{% block object-tools %}
    <ul class="object-tools">
        <li>
            {% if original.imovel %}
                <a href="{% url 'properties:fotos' original.imovel.id %}" target="_blank" class="historylink">Ver
                    fotos</a>
            {% else %}
                <a href="{% url 'properties:fotos' object_id %}" target="_blank" class="historylink">Ver
                    fotos</a>
            {% endif %}
        </li>
    </ul>
{% endblock %}

django/properties/templates/properties/fotos.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consultora Rayanne</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
</head>

<style>
    .photo-gallery {
        color: #313437;
        background-color: #fff;
    }

    .photo-gallery p {
        color: #7d8285;
    }

    .photo-gallery h2 {
        font-weight: bold;
        margin-bottom: 40px;
        padding-top: 40px;
        color: inherit;
    }

    @media (max-width: 767px) {
        .photo-gallery h2 {
            margin-bottom: 25px;
            padding-top: 25px;
            font-size: 24px;
        }
    }

    .photo-gallery .intro {
        font-size: 16px;
        max-width: 500px;
        margin: 0 auto 40px;
    }

    .photo-gallery .intro p {
        margin-bottom: 0;
    }

    .photo-gallery .photos {
        padding-bottom: 20px;
    }

    .photo-gallery .item {
        padding-bottom: 30px;
    }


</style>

<body>
<div class="photo-gallery">
    <div class="container">
        <div class="row">
            <div class="intro">
                <h2 class="text-center">{{ imovel }}</h2>
                {% if request.user.is_authenticated %}
                    <p class="text-center"><a href="/properties/imovel/{{ imovel.pk }}/change/">Editar Dados e Fotos</a></p>
                {% endif %}
                <p class="text-center">{% if imovel.descricao %}{{ imovel.descricao|linebreaksbr }}{% endif %}</p>

            </div>
            <div class="row photos">
                {% for foto in fotos %}
                    <div class="col-sm-6 col-md-4 col-lg-3 item"><a href="{{ foto.file.url }}"
                                                                    data-lightbox="photos"><img
                            class="img-fluid" src="{{ foto.file.url }}"></a></div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>
</body>

</html>